// GENERATED BY internal/gen/main.go. DO NOT EDIT!

package ptr

import "time"

// ToInt returns a pointer to x.
func ToInt(x int) *int { return &x }

// ToUint returns a pointer to x.
func ToUint(x uint) *uint { return &x }

// ToInt8 returns a pointer to x.
func ToInt8(x int8) *int8 { return &x }

// ToUint8 returns a pointer to x.
func ToUint8(x uint8) *uint8 { return &x }

// ToInt16 returns a pointer to x.
func ToInt16(x int16) *int16 { return &x }

// ToUint16 returns a pointer to x.
func ToUint16(x uint16) *uint16 { return &x }

// ToInt32 returns a pointer to x.
func ToInt32(x int32) *int32 { return &x }

// ToUint32 returns a pointer to x.
func ToUint32(x uint32) *uint32 { return &x }

// ToInt64 returns a pointer to x.
func ToInt64(x int64) *int64 { return &x }

// ToUint64 returns a pointer to x.
func ToUint64(x uint64) *uint64 { return &x }

// ToByte returns a pointer to x.
func ToByte(x byte) *byte { return &x }

// ToRune returns a pointer to x.
func ToRune(x rune) *rune { return &x }

// ToComplex64 returns a pointer to x.
func ToComplex64(x complex64) *complex64 { return &x }

// ToComplex128 returns a pointer to x.
func ToComplex128(x complex128) *complex128 { return &x }

// ToFloat32 returns a pointer to x.
func ToFloat32(x float32) *float32 { return &x }

// ToFloat64 returns a pointer to x.
func ToFloat64(x float64) *float64 { return &x }

// ToString returns a pointer to x.
func ToString(x string) *string { return &x }

// ToDuration returns a pointer to x.
func ToDuration(x time.Duration) *time.Duration { return &x }

// ToTime returns a pointer to x.
func ToTime(x time.Time) *time.Time { return &x }
